name: Quality Assurance
on: [push, pull_request]
jobs:
  assure-quality:
    name: Assure Quality
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: ğŸ‘ Invoke PSSA
        shell: pwsh
        run: |
          ./tests/_pssa.ps1

      - name: âœ… Invoke Pester
        shell: pwsh
        run: |
          ./tests/_pester.ps1
